name: 2025-book-env
channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.11 
- nb_conda_kernels
- ipykernel         
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- notebook >=7.0
- ipywidgets
- nbdime
- emcee
- ptemcee
- zeus-mcmc
- numdifftools
- corner
- scikit-learn
- scikit-image
- pydoe
- pytorch
- torchvision
- jupyter-book
- sphinx
- ghp-import
- arviz
- pip
- pip:
  - prettyplease
  - sphinx-proof
  - sphinx-inline-tabs
  - sphinx-exercise
  - myst_nb
  - gpy
  - gpyopt  
  - pymultinest
  - pymc

