name: 2025-env
channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.11 
- nb_conda_kernels
- ipykernel         
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- notebook >=7.0
- ipywidgets
- nbdime
- emcee
- ptemcee
- zeus-mcmc
- numdifftools
- corner
- scikit-learn
- scikit-image
- pydoe
- pip
- pip:
  - gpy
  - gpyopt  
  - pymultinest
  - pymc
  - pocomc

