name: lfd-book-env
channels:
- conda-forge
dependencies:
- python
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- emcee
- corner
- mkl-service
- scikit-learn
- scikit-image
- pymc3
- jupyter-book
- jupytext
- pip
- pip:
  - prettyplease
  - tensorflow
  - sphinx-proof
  - sphinx-inline-tabs
  - sphinx-exercise
  - myst_nb
